### ISSUE TITLE
Improve OD comparisons (centroid lines, palette)

### ISSUE THREAD

**Issue by cmcaine** [IntegratedTransportPlanning/gcvt#10]
It's a core user question.

**Comment by cmcaine** [comment]
Basic version done for links. Can be added to OD as we merge the apps or something.

**Comment by markjd84** [comment]
Basic version done for OD zones. Still needs 
* a more intelligent palette function (can we use same as for links?)
* an approach for when to draw centroid lines (do they make sense for comparisons? or do we just disable them)

**Comment by dbrenigjones** [comment]
#30
