### ISSUE TITLE
Summary statistics

### ISSUE THREAD

**Issue by dbrenigjones** [IntegratedTransportPlanning/gcvt#105]
Have a pane which is always shown which presents the summed total for either all links, all zones, or a selected link or zone. 

Care regarding links is needed because the summary statistics shouldn't be a straight summation of the chosen attribute, in some cases it should be a sum product. e.g. GHGs per km * link distance

Ideally it would also present the total for the EAP country the selected link or zone belongs to. And ideally it would also present the difference when comparing between scenarios.

**Comment by bovine3dom** [comment]
Show underneath zone selector. Show the "hovered over" value when a zone is clicked, or total if no zone is clicked. Show differences / percentage differences if selected. Only show on certain zones which we will specify in the meta.yaml. (Totals don't make sense for some variables).

Some link variables have corresponding zone variables and the totals should be taken from these instead, and shown underneath the link selector.

**Comment by bovine3dom** [comment]
David says:

The fields which would benefit from summary statistics are
Emissions GHGs
Emissions PMx
Emissions NOx
Energy use

**Comment by bovine3dom** [comment]
I've started on this in 0d7b041 - notable things left to do:

- fix bug where statistics aren't shown if zones are selected when the map is first loaded until zones are deselected
- only show for fields specified by meta.yaml
- show differences if compare mode is on

**Comment by bovine3dom** [comment]
This is done (but not deployed at the time of writing). There's a caveat in that "compare mode" is disabled if a zone is selected. The underlying code for statistics will work as soon as compare mode is enabled when zones are  selected, but I don't think that will happen before Monday. (I'm not sure why compare mode is disabled if a zone is selected - it seems like a conscious choice we made at some point).
