### ISSUE TITLE
Project locations doesn't work for lots of scenarios

### ISSUE THREAD

**Issue by bovine3dom** [IntegratedTransportPlanning/gcvt#109]
E.g. http://gcvt.cmcaine.co.uk/map/?linkVar=Project_Active&matVar=&scenario=GreenPort&scenarioYear=2030&percent=true&compare=false&showctrl=true&compareWith=DoNothing&compareYear=auto&showDesc=false&showClines=true&showMatHelp=true&showLinkHelp=true&showChart=true&selectedZones=[]#5.44/44.732/40.73 - looks like a data issue as the e.g. rail upgrades seem to work.

**Comment by cmcaine** [comment]
David says to remove that
