### ISSUE TITLE
Worklist for Wednesday meeting

### ISSUE THREAD

**Issue by cmcaine** [IntegratedTransportPlanning/gcvt#11]
- [x] Working scenario picker
   - [x] named list of scenario DFs
   - [x] just a selection box for now
- [x] Filter by mode
- [x] Weight style NULL
- [x] Highlight selected OD zone
- [x] Mouseover centroid lines
- [x] Bonus: graphs or scenario comparison

**Comment by markjd84** [comment]
You working on the scenario picker might be useful, I think we only need three things to pick by: package name (see examples); year (using slider) and country (maybe). Shiny's default use of selectize.js already allows type-to-filter, but not intuitively.  

I might claim these ones below if that's ok? :-) Haven't got my hands dirty with leaflet in here yet

- [ ] Highlight selected OD zone
- [ ] Mouseover centroid lines

**Comment by cmcaine** [comment]
Yes, those two sound good. There's already a linesFrom function in the od_viewer for generating the centroid-centroid lines, they'd just need to be styled and sent at the right times :)

**Comment by cmcaine** [comment]
I've been working on optional weight style and I'll move onto getting filters working.

**Comment by cmcaine** [comment]
Completed before meeting as planned.
