### ISSUE TITLE
Meeting notes 13/5/2020

### ISSUE THREAD

**Issue by cmcaine** [IntegratedTransportPlanning/gcvt#121]
David is showing stuff on the 22nd.

Try to deliver all of this by 20th/21st?

- Need new links and scenarios. @markjd84 to provide tomorrow
- Colin will integrate this data
- Logo @markjd84 to add
- Link widths - Need more info from David - Maybe the offsets aren't big enough? #120 http://gcvt.cmcaine.co.uk/map/#8.92/49.3045/32.2833
- UI Tweaks
  - @cmcaine will show @markjd84 the UI library and stuff, Mark will do the actual tweaks
- Domain name: greenerconnectivity.net -> CNAME for gcvt.cmcaine.co.uk
- Hosting transfer: mark will make a hetzner account at some point for transfer

**Comment by bovine3dom** [comment]
Domain transfer will need minor manual intervention on the WordPress installation and oEmbed plugin. I think I documented it somewhere.

**Comment by cmcaine** [comment]
These are now done or in other issues.
