### ISSUE TITLE
Scale styles by the range of variable across all scenarios

### ISSUE THREAD

**Issue by cmcaine** [IntegratedTransportPlanning/gcvt#14]
Pre-compute this, probably.

Can just rbind all the scenarios together into one big dataframe and find the range for each column. Or a for loop, whatever.

reStyling functions need to be adapted to take the range. Probably take a names list of VARIABLENAME -> RANGETUPLE

e.g.

"SPEED" -> 15, 150

in R:

list(SPEED = c(15, 150))

**Comment by markjd84** [comment]
Once this is done, there is a load of temporary UI that can be removed. 

Me and @dbrenigjones need to discuss

**Comment by markjd84** [comment]
Current thinking is that the problem remains that visualising within-scenario difference will be less obvious when styling using between-scenario stats

A nice solution might be to have a toggle switch between the two ways of calculating

**Comment by markjd84** [comment]
Solution computes min and max values across all scenarios for every indicator (whether links or zones)

Couldn't see how or why we'd do this for comparisons, and doesn't support quantiling, which would be possible but harder
