### ISSUE TITLE
Avoid system tippecanoe dep

### ISSUE THREAD

**Issue by bovine3dom** [IntegratedTransportPlanning/gcvt#145]
https://github.com/JuliaPackaging/BinaryBuilder.jl should make it pretty easy to make a `tippecanoe` binary package.

**Comment by bovine3dom** [comment]
Related: we're using `mb-utils` Python script to convert the `.mbtiles` to PBF.

I'm not sure what the best way of including that dependency is. We could switch to e.g. a server we can install with `yarn` https://github.com/DenisCarriere/mbtiles-server and skip the conversion to PBF.

**Comment by markjd84** [comment]
Huh, I just got wondering about this, and it looks like `tippecanoe --output-to-directory=blah` will just produce PBFs to appropriately nested directories, which can then be served however. 

I don't know if that might get us out of using `mb-utils` altogether?

**Comment by markjd84** [comment]
```
mark@integac7:~/tippecanoe$ tippecanoe -f --output-to-directory=tester/ -l cities --no-feature-limit --no-tile-size-limit -z10 world.geojson
391545 features, 12952203 bytes of geometry, 2 bytes of separate metadata, 11471431 bytes of string pool
  99.9%  10/598/343
mark@integac7:~/tippecanoe$ ls tester/
0  1  10  2  3  4  5  6  7  8  9  metadata.json
mark@integac7:~/tippecanoe$ cd tester/0/0/
mark@integac7:~/tippecanoe/tester/0/0$ l
total 124
-rw-rw-r-- 1 mark mark 125038 Feb  9 17:25 0.pbf

```

**Comment by bovine3dom** [comment]
That's great! I searched through the help for "PBF" but didn't see it so I gave up. Thanks for being more thorough : )

**Comment by cmcaine** [comment]
This is good :)

> We could switch to e.g. a server we can install with yarn https://github.com/DenisCarriere/mbtiles-server and skip the conversion to PBF.

I prefer that we generate the tiles ahead of time. I don't know if PostGIS does it, but the two other "tiles servers" that I've seen generate the tiles on-demand and then cache them. Given that our geometry is much smaller than our disk space, we might as well skip the complexity and one-off latency and do it once.

**Comment by bovine3dom** [comment]
100% agree given that we can probably just use `tippecanoe`. Probably 95% agree if we have to keep using `mb-utils` :)
