### ISSUE TITLE
Design guided/simple story UI

### ISSUE THREAD

**Issue by cmcaine** [IntegratedTransportPlanning/gcvt#18]
Perhaps the user picks a scenario and a few one line stories are suggested somewhere?

"See difference in travel time now that border control is relaxed" -> Preset options (compare scenario with baseline in OD view with variable travel time)

**Comment by markjd84** [comment]
Keen to work on this one next week. Think it would allow me to further get my hands dirty understanding Shiny's interactivity. We also worked on something similar in Django tho it wasn't used well.

We may also want to think about how metadata might capture this info plus any other more fundamental scenario info (do we want to run any checks on attributes/matrices? Or just see what files are there and present them as loadable?). Related to #7

**Comment by cmcaine** [comment]
Ref: #40, #9
