### ISSUE TITLE
Centroid to centroid lines in OD viewer

### ISSUE THREAD

**Issue by cmcaine** [IntegratedTransportPlanning/gcvt#2]

**Comment by Robinlovelace** [comment]
Sounds good!

**Comment by cmcaine** [comment]
I think we should just generate these on the fly because showing all `N(N+1)` lines is a bit much.

A nice visualisation might be to highlight all *links* out of a zone by e.g. how much tonnage they're providing. Would require the modellers to capture that information, but I think it would be pretty cool and also quite useful to see how each link contributes to the total stat for the region.

If our source OD data is in the right format we may want to use od2line from Robin's stplanr package, but I don't think we'll want to get the geometry that way. It'll be better to just generate it on the fly, I think.

@Robinlovelace btw, od2line2 doesn't work for me. Tested `stplanr::od2line2(stplanr::flow, stplanr::cents)` and got an empty object back.

**Comment by cmcaine** [comment]
Enabled this on hover, but it's a bit too slow so we'll just have to do it in JS.

Showing all lines isn't readable. Maybe showing the top N by value or something would be useful?

**Comment by cmcaine** [comment]
@dbrenigjones suggests top N lines with transparency and shows that that provides insight when drawn for all zones, or for a selection of zones.

Suggests selecting multiple zones to show centroid lines between them.

If lines are drawn on click the method already implemented may be fast enough. Otherwise we'll need custom JS again.

**Comment by markjd84** [comment]
Might suggest that I take over what remains of this one? (Now @cmcaine did all the difficult bits? :) )

**Comment by markjd84** [comment]
Couple of minor bits outstanding

* Currently the reStyle() code seems to take a single value for selected, but we now need it to be several. Couldn't figure out how to fix this looking at your Leaflet fork, sorry :)
* Also doesn't yet listen for a modifier key, had a bit of a look through shiny/leaflet docs but no cigar

**Comment by markjd84** [comment]
[This](https://github.com/rstudio/leaflet/blob/7de631d4966b9eb25b22bcbcd68f21bc2617e7a2/docs/libs/leaflet-binding/leaflet.js#L654) may be one place to do it if we need to get modifier keys (not sure which version of the binding we are on though)

**Comment by cmcaine** [comment]
You don't need to look at the styling code at that level of detail.

Restyling zones currently uses two function calls. One to setStyleFast to style all the polygons and then another to setStyle to style a single polygon.

All you need to do is work out what to style all the polygons by if you select more than one polygon (Would sum of "from" values from each selected region make sense? I think so), and then wrap the setStyle call in a loop and apply it to each selected zone.

Remember to assign back to `map` with each call and to return `map` at the end of the function.

Something like this:

```R
map = map %>% setStyleFast(blah) %>% addAutoLegend(blah)
for (zone in selected) {
  map = setStyle(map, blah, blah, blah)
}
```

**Comment by cmcaine** [comment]
re: modifier keys, yes, that's the place to edit. We're on my fork of Leaflet, which is basically up to date with the main development branch.

**Comment by markjd84** [comment]
I opted for ctrl-click to select as shift-click seemed to have other behaviour associated with it

**Comment by cmcaine** [comment]
Fixed some bugs with deselecting.
