### ISSUE TITLE
Add new origins/destinations - update the input zone file

### ISSUE THREAD

**Issue by Robinlovelace** [IntegratedTransportPlanning/gcvt#24]

**Comment by cmcaine** [comment]
Missing zones (N is the ID_CUBE attribute in the skim data).

Zone N= 235       North America

Zone N= 236       South America

Zone N= 234       Africa

Zone N= 229       Arabia Peninsula

Zone N= 231       India, Nepal, Bhutan

Zone N= 233       South East Asia

Zone N= 237       Australia Oceania Antarctics

Zone N= 232       East Asia

**Comment by markjd84** [comment]
Probably worth being aware we might not actually *need* accurate geography for this - as I expect the only zones we will actually want to visualise will be those neighbouring the EAP. Sorry, should have thought of this before

**Comment by cmcaine** [comment]
Done, thanks Mark
