### ISSUE TITLE
gcvt package cannot be installed

### ISSUE THREAD

**Issue by Robinlovelace** [IntegratedTransportPlanning/gcvt#25]

**Comment by Robinlovelace** [comment]
[reprex](https://github.com/tidyverse/reprex): 

``` r
devtools::install_github("IntegratedTransportPlanning/gcvt")
#> Using GitHub PAT from envvar GITHUB_PAT
#> Downloading GitHub repo IntegratedTransportPlanning/gcvt@master
#> from URL https://api.github.com/repos/IntegratedTransportPlanning/gcvt/zipball/master
#> Installation failed: Timeout was reached: Operation timed out after 0 milliseconds with 0 out of 0 bytes received
```

Created on 2018-07-22 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by Robinlovelace** [comment]
```
Error in parse(outFile) : 
  /tmp/RtmpPXOT2C/devtools3e061b559ed2/IntegratedTransportPlanning-gcvt-e55611b/R/scraps.R:95:9: unexpected '['
94: 
95: links = [
            ^
ERROR: unable to collate and parse R files for package ‘gcvt’
* removing ‘/home/robin/R/x86_64-pc-linux-gnu-library/3.5/gcvt’
* restoring previous ‘/home/robin/R/x86_64-pc-linux-gnu-library/3.5/gcvt’
Installation failed: Command failed (1)
```

**Comment by cmcaine** [comment]
scraps is not an important file. It's just working notes. We can comment it
all out to fix this.

**Comment by Robinlovelace** [comment]
R packages try to run all files in `R/` so heads-up: I plan to move some things around.

**Comment by cmcaine** [comment]
I think Mark broke this again, so we'll have to fix it up later.

**Comment by Robinlovelace** [comment]
Just tested - worked fine just now:

```
devtools::install_github("IntegratedTransportPlanning/gcvt")
Using GitHub PAT from envvar GITHUB_PAT
Downloading GitHub repo IntegratedTransportPlanning/gcvt@master
from URL https://api.github.com/repos/IntegratedTransportPlanning/gcvt/zipball/master
Installing gcvt
Using GitHub PAT from envvar GITHUB_PAT
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/tmp/Rtmpr46yel/devtools637e69f3a61c/IntegratedTransportPlanning-gcvt-3203d62'  \
  --library='/home/robin/R/x86_64-pc-linux-gnu-library/3.5'  \
  --install-tests 

* installing *source* package ‘gcvt’ ...
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (gcvt)
```

**Comment by markjd84** [comment]
Sorry only just now looking at this issue - is there anything specific I need to know about keeping code buildable for R packages, or did I just do something silly :-) @cmcaine

**Comment by cmcaine** [comment]
You didn't do anything wrong, Mark, I just thought you might have done by moving the shiny apps back into the R/ directory.

Turns out R packages try to run all the code in the R/ directory, but not shiny apps or something? If they did try to run those they would fail, anyway.

**Comment by Robinlovelace** [comment]
It's a good question and it seems there's no definitive answer. According to prolific shiny developer Dean Attali you should put the app in `inst`, which is where extras associated with a package go (e.g. `inst/data`):

> Then place your Shiny app folder under inst/shiny-examples/ and add an R file called runExample.R. The package’s tree structure should look like this

```
- mypacakge
  |- inst
     |- shiny-examples
        |- myapp
           |- ui.R
           |- server.R
  |- R
     |- runExample.R
     |- ...
  |- DESCRIPTION
  |- ...
```

**Comment by Robinlovelace** [comment]
However, the most useful in-package app I use puts it all in the `R` directory so I think we're fine: https://github.com/crsh/citr/blob/master/R/insert_citation.R also this awesome app is in the R dir: https://github.com/gadenbuie/regexplain/blob/master/R/regex_gadget.R

In summary I think it's fine as-is: R code that we want to run on attaching the package or shiny apps go in `R`, everything else can go in `code` or elsewhere - we'd need to tidy this up if the plan were to submit it to CRAN but I don't think that's the plan.
