### ISSUE TITLE
Improve line styling

### ISSUE THREAD

**Issue by cmcaine** [IntegratedTransportPlanning/gcvt#27]
Don't want to fade to white. Try a larger range of widths.

**Comment by cmcaine** [comment]
Trialing better colours.

**Comment by markjd84** [comment]
I am just working on something which will allow user to select a colorbrewer palette. This will probably only be used temporarily, as long term we may want to force users to live with our decisions :)

**Comment by dbrenigjones** [comment]
As the user can now select a color brewer palette - is this issue dealt with?
