### ISSUE TITLE
Improve zones

### ISSUE THREAD

**Issue by Robinlovelace** [IntegratedTransportPlanning/gcvt#35]
- [ ] Remove slivers
- [ ] Make them contiguous
- [ ] Consistent level of simplification

I've already tried and failed on this so not promising anything - just thought I'd flag it as something I can look at. Any others I should look at?

**Comment by dbrenigjones** [comment]
I think it is the responsibility of the modeller to correctly prepare the zone shapefile

**Comment by Robinlovelace** [comment]
Fair enough. Could you pass on these concerns to the modellers?
