### ISSUE TITLE
Style link width by variable

### ISSUE THREAD

**Issue by cmcaine** [IntegratedTransportPlanning/gcvt#4]

**Comment by cmcaine** [comment]
Got this working locally. Guidance on what to scale variables by (their own column, related columns, global column, global related) appreciated.

I'll go through the questions again and write up something we can send to the WB or pass around people at ITP who have done relevant work in this area.

**Comment by markjd84** [comment]
Thanks. I'll do some asking around about users and questions later in the week

**Comment by cmcaine** [comment]
Done
