### ISSUE TITLE
Year slider

### ISSUE THREAD

**Issue by markjd84** [IntegratedTransportPlanning/gcvt#41]
Does not currently do anything

Also see #34 - scenario picker outside 'layer control' groups

Both issues require some careful thinking about the UI. Might we (eg) want to see comparison of link datasets whilst viewing zone stats (or vice versa?). Is there a situation in which we'd want to see different years at same time? (can't think of one, but don't want to rule out)

**Comment by Robinlovelace** [comment]
Discussing with @cmcaine and suggest we implement when we have the data. Do we have a range of scenario data? Not in the data folder. Can simulate if not.

**Comment by markjd84** [comment]
Data is due to come in probably next week. Good plan - don't think this is a difficult one!
