### ISSUE TITLE
Reduce initial load time

### ISSUE THREAD

**Issue by cmcaine** [IntegratedTransportPlanning/gcvt#42]
Reduce data volume:
 - Compress data (better?) before sending it
 - Half link data by only sending one direction of each link pair

Vector tiles:
 - Create and serve tiles in the mapbox vector tile format (Only download detailed information for areas you zoom into)
 - t_rex serves and generates MVT protobufs, but it's extremely slow at generating them, this could be because I'm generating from geojson, I think if I load the geom into postgis it will get simplified more appropriately and work faster.
 - geojson_vt is very fast, but the total size of the tiles generated is huge (~30x bigger than original geojson)

**Comment by Robinlovelace** [comment]
Sounds like a big mission! Look forward to testing.

**Comment by markjd84** [comment]
Using Mapbox GL is fast enough that I think we can close this.
