### ISSUE TITLE
Excessive output in default popups in network mode

### ISSUE THREAD

**Issue by Robinlovelace** [IntegratedTransportPlanning/gcvt#45]
To the point where it's overwhelming, reducing user-friendliness and moves the map view when you click on a link. Example view:

![image](https://user-images.githubusercontent.com/1825120/45105552-640c3880-b12c-11e8-8411-0faca00be7a6.png)

**Comment by markjd84** [comment]
Some progress (as we dropped columns using middleware) but still not got friendly names etc.
