### ISSUE TITLE
Remaining mapbox integration tasks

### ISSUE THREAD

**Issue by markjd84** [IntegratedTransportPlanning/gcvt#47]
Made some tweaks and got a test version running at http://integac7.miniserver.com:4402/

Performance seems to be good (so it's just my VM being sluggish!) 

However, still need to 
- [x] test zone click+select interactivity, and 'scenario difference' modes
- [x] draw legend
- [x] work out how to show selected zones (`fill-outline-color` seems to be all that is supported, other options?)
- [x] draw centroid lines
- [x] render popup on links
- [x] make `mapbox` the master branch
- [x] render hover label on links and zones
- [x] work out (and fix!) what is going on with Kaliningrad.

**Comment by markjd84** [comment]
Legends were a pain, plus a couple of minor bugs I haven't been able to fix yet. Leaving it for now cos it kinda works :-(

**Comment by Robinlovelace** [comment]
@cmcaine let me know if/when the master branch changes. Suspect I'll need to reclone after that, will see how clever git is!

**Comment by cmcaine** [comment]
I merged mapbox into master. You'll just need to

```sh
git checkout master
git pull
```

Unless your branch is dirty or something.

**Comment by Robinlovelace** [comment]
Awesome. 4 down 2 to go.

**Comment by Robinlovelace** [comment]
It worked :rocket:

**Comment by markjd84** [comment]
Cheers guys! Leave the remaining 2 to me, I've got stuff I've been working on for the first of them and useful to get my head around mapbox.

**Comment by markjd84** [comment]
bc33e43480caa932ff9a445c8609350a139068a1 fixes the Kaliningrad issue for now, caused by our geojson IDs starting at 1. 

However need a proper fix which styles links by IDs instead of indexes: #52
