### ISSUE TITLE
Legend isn't as nice as the Leaflet one

### ISSUE THREAD

**Issue by cmcaine** [IntegratedTransportPlanning/gcvt#48]
The legend that R Leaflet gives you isn't provided by leaflet.js, it's something that the rstudio developers wrote.

We can fairly easily port it for mapbox because it doesn't depend on leaflet very much.

The function is here: https://github.com/cmcaine/leaflet/blob/012bec5a774547c6589beacfdc9a02d8d64fc9bb/javascript/src/methods.js#L765

I think the code to do it should live in the JS rather than R, then we can maintain more of a split between presentation code and the logic about what should be displayed.

**Comment by markjd84** [comment]
Sounds good. Yeh I invested a bit of time but it wasn't really working nicely, for all sorts of reasons. Yeh I can try and bring this in or if you have any advice on doing so that'd be great.

**Comment by cmcaine** [comment]
The code is pretty self contained, but it's not terribly well written.

If you just want to do a quick job, I would add jquery to the project so that you can use the same $ function they use and then just paste it in. The only bits you'll need to replace are those starting `L.` and `map.`

The most complicated of those is `L.control` which creates a simple object. This function just adds an attribute `onAdd` that is a function that leaflet will call when the control is added to the map.

Instead of that, we'll just create our div and add it straight to document.body. For now, I'd just write it to handle one legend at a time, so make a div with id=legend and just replace it each time the function is called, but in the future we'll want to keep track of the legends we have and display multiple legends.

If you find yourself rewriting it a lot, I'd advise you to use the Mithril framework, which is a nice and simple JS frontend framework.

**Comment by markjd84** [comment]
Still needs fixing after metadata rewrite, which I can quickly attempt

![image](https://user-images.githubusercontent.com/6650143/50091368-18752a80-0203-11e9-8136-b1a3426a0625.png)
