### ISSUE TITLE
Links are showing in blue prior to layer being turned on

### ISSUE THREAD

**Issue by markjd84** [IntegratedTransportPlanning/gcvt#49]
Something to do with `hideLayer()` not quite getting called at right time?

**Comment by cmcaine** [comment]
I think the logic of the deferring function calls at the end of app.js is
broken by having links *and* zones.

So only the last hidelayer call is retained.

One solution would be to key on a tuple of function and group. Beware that
identical arrays are not equal in js and will count as different keys (as I
recall). You can get around that by using Immutable.js (I think) or by
using a map of maps.
