### ISSUE TITLE
Improve CSS for side menu

### ISSUE THREAD

**Issue by cmcaine** [IntegratedTransportPlanning/gcvt#5]

**Comment by cmcaine** [comment]
I fixed the dropdown being in the wrong place. Further improvements possible.

**Comment by markjd84** [comment]
Put in a few more controls and experimented with different Shiny features. 

The CSS still needs a lot of polish (and some drawing problems resolved) but I can sort this

**Comment by cmcaine** [comment]
You can include other css from one stylesheet with the `@import` directive in css: https://developer.mozilla.org/en-US/docs/Web/CSS/@import

That should solve the bootswatch issue.

**Comment by cmcaine** [comment]
I fixed the other issues.

**Comment by markjd84** [comment]
Cheers. The `@import` directive doesnt work well, I presume because Shiny is already loading Bootstrap CSS prior to the app seeing that. Googling didn't find a neat result, but since vanilla bootstrap still looks pretty good I might leave this for now.

**Comment by markjd84** [comment]
`importCSS()` was what I was looking for

Have switched in a bootswatch theme for sidebar for now, it's a bit loud :-)

**Comment by markjd84** [comment]
Some remaining (lower priority) tweaks

- [ ] dropdowns do not open fully/outside panel
- [ ] +/- on expanding of box
- [ ] set the widths of elements consistently
- [ ] pick a nicer style from shinythemes
