### ISSUE TITLE
Popups need work

### ISSUE THREAD

**Issue by markjd84** [IntegratedTransportPlanning/gcvt#67]
* Read variable names from metadata (we already use them elsewhere, so just needs wiring up) 
* Format numbers appropriately (3 s.f.s? units?) 

![image](https://user-images.githubusercontent.com/6650143/54198595-d0426d00-44be-11e9-84e1-a9a1b4dd2e17.png)

**Comment by cmcaine** [comment]
The current popups give different information, so this isn't relevant any more.
