### ISSUE TITLE
Need UI for picking dataset/scenario

### ISSUE THREAD

**Issue by cmcaine** [IntegratedTransportPlanning/gcvt#7]
type to filter style select box would do fine

**Comment by markjd84** [comment]
If we keep our 'project' screen which will eventually allow setting up of metadata etc, it might be useful for it to summarise the scenarios against years available in a nice table format, with a tick or warning according to whether data has been found, parsed successfully, etc. Of course that could be costly in loading, checking each but just an idea.

**Comment by markjd84** [comment]
The original idea behind this was to provide some func/ty to allow easy uploading of new model data etc. But increasingly seeming that may not be needed (yet)

**Comment by markjd84** [comment]
I think this is half-done, and half not needed. If we decide we want a UI to load projects we can reopen
