### ISSUE TITLE
Travel GC freight doesn't work

### ISSUE THREAD

**Issue by bovine3dom** [IntegratedTransportPlanning/gcvt#99]
From the Google Doc: "this could be a problem with the data/ITP's fault" - I'm not sure what this means.

**Comment by bovine3dom** [comment]
http://gcvt.cmcaine.co.uk/map/?linkVar=&matVar=TravelCost_freight&scenario=GreenMax&scenarioYear=2030&percent=false&compare=false&showctrl=true&compareWith=DoNothing&compareYear=auto&showDesc=false&showClines=false&showMatHelp=true&showLinkHelp=false&showChart=true&selectedZones=[1]#4.45/48.47/40.32

e.g. from kiev, northern europe and azerbaijan very easy to get to but southern ukraine is expensive

**Comment by cmcaine** [comment]
Seems fixed: http://gcvt.cmcaine.co.uk/map/?linkVar=&matVar=TravelCost_freight&scenario=FleetElectric&scenarioYear=2030&percent=false&compare=false&showctrl=true&compareWith=DoNothing&compareYear=auto&showDesc=false&showClines=false&showMatHelp=true&showLinkHelp=false&showChart=true&selectedZones=[1]#4.56/48.28/39.69
